# Generated by Django 5.2.7 on 2025-12-19 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("full_name", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=20)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("parent", "Parent"),
                            ("doctor", "Doctor"),
                            ("admin", "Admin"),
                        ],
                        default="parent",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("license_number", models.CharField(max_length=100)),
                ("certificate_url", models.URLField(blank=True, null=True)),
                ("specialization", models.CharField(blank=True, max_length=255)),
                ("is_approved", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Household",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("has_mother", models.BooleanField(default=True)),
                ("has_father", models.BooleanField(default=True)),
                ("siblings_count", models.PositiveIntegerField(default=0)),
                ("has_maternal_grandparents", models.BooleanField(default=False)),
                ("has_paternal_grandparents", models.BooleanField(default=False)),
                ("has_uncle_aunt", models.BooleanField(default=False)),
                ("has_other_relatives", models.BooleanField(default=False)),
                ("has_helper", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="household",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ParentDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mother_name", models.CharField(blank=True, max_length=255)),
                ("mother_age", models.PositiveIntegerField(blank=True, null=True)),
                ("mother_occupation", models.CharField(blank=True, max_length=255)),
                ("father_name", models.CharField(blank=True, max_length=255)),
                ("father_age", models.PositiveIntegerField(blank=True, null=True)),
                ("father_occupation", models.CharField(blank=True, max_length=255)),
                (
                    "primary_caregiver",
                    models.CharField(
                        choices=[
                            ("mother", "Mother"),
                            ("father", "Father"),
                            ("grandparent", "Grandparent"),
                            ("other", "Other"),
                        ],
                        default="mother",
                        max_length=20,
                    ),
                ),
                (
                    "primary_caregiver_other",
                    models.CharField(blank=True, max_length=255),
                ),
                ("home_address", models.TextField(blank=True)),
                ("municipality", models.CharField(blank=True, max_length=255)),
                ("district", models.CharField(blank=True, max_length=255)),
                (
                    "province",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1", "Province 1"),
                            ("2", "Province 2"),
                            ("bagmati", "Bagmati"),
                            ("gandaki", "Gandaki"),
                            ("lumbini", "Lumbini"),
                            ("karnali", "Karnali"),
                            ("sudurpaschim", "Sudurpaschim"),
                        ],
                        max_length=20,
                    ),
                ),
                ("primary_phone", models.CharField(blank=True, max_length=20)),
                ("has_whatsapp", models.BooleanField(default=False)),
                ("secondary_phone", models.CharField(blank=True, max_length=20)),
                (
                    "smartphone_comfort",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("very_comfortable", "Very Comfortable"),
                            ("somewhat_comfortable", "Somewhat Comfortable"),
                            ("need_help", "Need Help"),
                            ("not_comfortable", "Not Comfortable"),
                        ],
                        max_length=30,
                    ),
                ),
                ("consent_followup", models.BooleanField(default=False)),
                ("consent_research", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_details",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
