# Generated by Django 5.2.7 on 2025-12-19 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("children", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssessmentVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "video_type",
                    models.CharField(
                        choices=[
                            ("walking", "Walking"),
                            ("eating", "Eating"),
                            ("speaking", "Speaking"),
                            ("behavior", "Behavior"),
                            ("playing", "Playing"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("video_url", models.URLField(help_text="Cloudflare Stream URL")),
                ("description", models.TextField(blank=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="children.child",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="ChildAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("in_review", "In Review"),
                            ("accepted", "Accepted by Doctor"),
                            ("completed", "Assessment Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("parent_confirmed", models.BooleanField(default=False)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_patients",
                        to="accounts.doctor",
                    ),
                ),
                (
                    "child",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessment",
                        to="children.child",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MChatResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "q1",
                    models.BooleanField(
                        help_text="Points & looks at what you point to"
                    ),
                ),
                ("q2", models.BooleanField(help_text="Wondered if deaf (REVERSE)")),
                ("q3", models.BooleanField(help_text="Pretend play")),
                ("q4", models.BooleanField(help_text="Likes climbing")),
                (
                    "q5",
                    models.BooleanField(help_text="Unusual finger movements (REVERSE)"),
                ),
                ("q6", models.BooleanField(help_text="Points to ask for something")),
                ("q7", models.BooleanField(help_text="Points to show something")),
                ("q8", models.BooleanField(help_text="Interested in other children")),
                ("q9", models.BooleanField(help_text="Shows things to share")),
                ("q10", models.BooleanField(help_text="Responds to name")),
                ("q11", models.BooleanField(help_text="Smiles back")),
                (
                    "q12",
                    models.BooleanField(help_text="Upset by everyday noises (REVERSE)"),
                ),
                ("q13", models.BooleanField(help_text="Walks")),
                ("q14", models.BooleanField(help_text="Eye contact")),
                ("q15", models.BooleanField(help_text="Copies actions")),
                ("q16", models.BooleanField(help_text="Follows gaze")),
                ("q17", models.BooleanField(help_text="Seeks attention")),
                ("q18", models.BooleanField(help_text="Understands commands")),
                ("q19", models.BooleanField(help_text="Checks reactions")),
                ("q20", models.BooleanField(help_text="Likes movement activities")),
                ("total_score", models.PositiveIntegerField(default=0)),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low Risk (0-2)"),
                            ("medium", "Medium Risk (3-7)"),
                            ("high", "High Risk (8-20)"),
                        ],
                        default="low",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "child",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mchat",
                        to="children.child",
                    ),
                ),
            ],
            options={
                "verbose_name": "M-CHAT Response",
                "verbose_name_plural": "M-CHAT Responses",
            },
        ),
    ]
