# Generated by Django 5.2.7 on 2025-12-19 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessmentvideo",
            name="video_url",
            field=models.TextField(help_text="Video URL or local file path"),
        ),
    ]
