# Generated by Django 5.2.7 on 2025-12-19 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("children", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Curriculum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "duration_days",
                    models.PositiveIntegerField(help_text="15, 30, or 45 days"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("specialized", "Specialized"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                (
                    "spectrum_type",
                    models.CharField(
                        blank=True,
                        help_text="For specialized curriculum only",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_curricula",
                        to="accounts.doctor",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Curricula",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChildCurriculum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("current_day", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_curricula",
                        to="accounts.doctor",
                    ),
                ),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="curricula",
                        to="children.child",
                    ),
                ),
                (
                    "curriculum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_assignments",
                        to="therapy.curriculum",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Child Curricula",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CurriculumTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_number",
                    models.PositiveIntegerField(help_text="Day 1 to duration_days"),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "why_description",
                    models.TextField(help_text="Why this task matters for the child"),
                ),
                (
                    "instructions",
                    models.TextField(help_text="Step-by-step instructions for parents"),
                ),
                (
                    "demo_video_url",
                    models.URLField(blank=True, help_text="Demo video URL"),
                ),
                (
                    "order_index",
                    models.PositiveIntegerField(
                        default=0, help_text="Order within the day"
                    ),
                ),
                (
                    "curriculum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="therapy.curriculum",
                    ),
                ),
            ],
            options={
                "ordering": ["day_number", "order_index"],
            },
        ),
        migrations.CreateModel(
            name="DoctorReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "review_period",
                    models.PositiveIntegerField(help_text="Day 15, 30, or 45"),
                ),
                ("observations", models.TextField()),
                ("spectrum_identified", models.CharField(blank=True, max_length=100)),
                ("recommendations", models.TextField()),
                ("reviewed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "child_curriculum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="therapy.childcurriculum",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviews",
                        to="accounts.doctor",
                    ),
                ),
            ],
            options={
                "ordering": ["-reviewed_at"],
            },
        ),
        migrations.CreateModel(
            name="DailyProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day_number", models.PositiveIntegerField()),
                ("date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_done", "Not Done"),
                            ("done_with_help", "Done with Help"),
                            ("done_without_help", "Done without Help"),
                        ],
                        default="not_done",
                        max_length=20,
                    ),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True, help_text="Video of child doing the task"
                    ),
                ),
                ("parent_notes", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "child_curriculum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_entries",
                        to="therapy.childcurriculum",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_entries",
                        to="therapy.curriculumtask",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Daily Progress",
                "ordering": ["-date", "-submitted_at"],
                "unique_together": {("child_curriculum", "task", "date")},
            },
        ),
    ]
