# Generated by Django 5.2.7 on 2025-12-19 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("children", "0001_initial"),
        ("therapy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiagnosisReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "has_autism",
                    models.BooleanField(
                        help_text="Diagnosis result: has autism or not"
                    ),
                ),
                (
                    "spectrum_type",
                    models.CharField(
                        choices=[
                            ("none", "No Autism Detected"),
                            ("mild", "Mild (Level 1 - Requiring Support)"),
                            (
                                "moderate",
                                "Moderate (Level 2 - Requiring Substantial Support)",
                            ),
                            (
                                "severe",
                                "Severe (Level 3 - Requiring Very Substantial Support)",
                            ),
                        ],
                        default="none",
                        help_text="Autism spectrum severity level",
                        max_length=20,
                    ),
                ),
                (
                    "detailed_report",
                    models.TextField(help_text="Detailed findings and observations"),
                ),
                (
                    "next_steps",
                    models.TextField(
                        help_text="Recommended next steps and interventions"
                    ),
                ),
                (
                    "shared_with_parent",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this report is visible to parents",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diagnosis_reports",
                        to="children.child",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="diagnosis_reports",
                        to="accounts.doctor",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
