# Generated by Django 5.2.7 on 2025-12-19 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("therapy", "0002_diagnosisreport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyprogress",
            name="video_url",
            field=models.TextField(
                blank=True,
                help_text="Video of child doing the task (local path or URL)",
            ),
        ),
    ]
