# Generated by Django 5.2.7 on 2025-12-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("therapy", "0003_change_video_url_to_textfield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="curriculum",
            name="type",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("specialized", "Specialized"),
                    ("assessment", "Pre-Assessment"),
                ],
                default="general",
                max_length=20,
            ),
        ),
    ]
