# Generated by Django 6.0 on 2026-01-18 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("children", "0002_alter_childhealth_has_vaccinations"),
        ("therapy", "0004_alter_curriculum_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="curriculum",
            name="for_child",
            field=models.ForeignKey(
                blank=True,
                help_text="If set, this is a personalized curriculum for a specific child",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="personalized_curricula",
                to="children.child",
            ),
        ),
        migrations.AddField(
            model_name="curriculum",
            name="is_template",
            field=models.BooleanField(
                default=True,
                help_text="If True, this is a reusable template. If False, it's child-specific.",
            ),
        ),
        migrations.AddField(
            model_name="curriculum",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("published", "Published")],
                default="published",
                help_text="Draft curricula are only visible to the creating doctor",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="curriculum",
            name="duration_days",
            field=models.PositiveIntegerField(
                help_text="Number of days (e.g., 3, 7, 15, 30)"
            ),
        ),
        migrations.AlterField(
            model_name="curriculum",
            name="type",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("specialized", "Specialized"),
                    ("assessment", "Pre-Assessment"),
                    ("personalized", "Personalized"),
                ],
                default="general",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="SavedTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("goal", models.TextField(help_text="What this task aims to achieve")),
                (
                    "instructions",
                    models.TextField(help_text="Step-by-step instructions for parents"),
                ),
                ("video_url", models.URLField(blank=True, help_text="Demo video URL")),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="Optional category for organization (e.g., 'Communication', 'Motor Skills')",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_tasks",
                        to="accounts.doctor",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("doctor", "title")},
            },
        ),
    ]
