# Generated by Django 5.2.7 on 2025-12-19 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Child",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("date_of_birth", models.DateField()),
                ("age_years", models.PositiveIntegerField()),
                ("age_months", models.PositiveIntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Children",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChildEducation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("goes_to_school", models.BooleanField(default=False)),
                ("school_name", models.CharField(blank=True, max_length=255)),
                ("grade_class", models.CharField(blank=True, max_length=50)),
                (
                    "school_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("government", "Government"),
                            ("private", "Private"),
                            ("special", "Special School"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "transport_mode",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("walk", "Walk"),
                            ("bus", "Bus"),
                            ("private_vehicle", "Private Vehicle"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("wake_up_time", models.TimeField(blank=True, null=True)),
                ("breakfast_time", models.TimeField(blank=True, null=True)),
                ("school_start_time", models.TimeField(blank=True, null=True)),
                ("school_end_time", models.TimeField(blank=True, null=True)),
                ("lunch_time", models.TimeField(blank=True, null=True)),
                ("nap_start_time", models.TimeField(blank=True, null=True)),
                ("nap_end_time", models.TimeField(blank=True, null=True)),
                ("evening_activities", models.TextField(blank=True)),
                ("dinner_time", models.TimeField(blank=True, null=True)),
                ("sleep_time", models.TimeField(blank=True, null=True)),
                (
                    "child",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="education",
                        to="children.child",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChildHealth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "height_cm",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "weight_kg",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "has_vaccinations",
                    models.CharField(
                        choices=[
                            ("yes", "Yes"),
                            ("no", "No"),
                            ("not_sure", "Not Sure"),
                        ],
                        default="not_sure",
                        max_length=10,
                    ),
                ),
                (
                    "medical_conditions",
                    models.TextField(
                        blank=True, help_text="Current medical conditions"
                    ),
                ),
                ("takes_medication", models.BooleanField(default=False)),
                ("medication_list", models.TextField(blank=True)),
                ("seen_pediatrician", models.BooleanField(default=False)),
                ("seen_psychiatrist", models.BooleanField(default=False)),
                ("seen_speech_therapist", models.BooleanField(default=False)),
                ("seen_occupational_therapist", models.BooleanField(default=False)),
                ("seen_psychologist", models.BooleanField(default=False)),
                ("seen_special_educator", models.BooleanField(default=False)),
                ("seen_neurologist", models.BooleanField(default=False)),
                ("seen_traditional_healer", models.BooleanField(default=False)),
                ("seen_none", models.BooleanField(default=False)),
                (
                    "child",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health",
                        to="children.child",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MedicalHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pregnancy_infection", models.BooleanField(default=False)),
                ("pregnancy_infection_desc", models.TextField(blank=True)),
                ("birth_complications", models.BooleanField(default=False)),
                ("birth_complications_desc", models.TextField(blank=True)),
                ("brain_injury_first_year", models.BooleanField(default=False)),
                ("brain_injury_desc", models.TextField(blank=True)),
                ("family_autism_history", models.BooleanField(default=False)),
                ("requires_specialist", models.BooleanField(default=False)),
                (
                    "child",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_history",
                        to="children.child",
                    ),
                ),
            ],
        ),
    ]
