# Generated by Django 6.0 on 2025-12-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("children", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="childhealth",
            name="has_vaccinations",
            field=models.CharField(
                choices=[
                    ("complete", "Complete"),
                    ("incomplete", "Incomplete"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                max_length=10,
            ),
        ),
    ]
